import { ReactionContent } from "./models";

export const reactions: ReactionContent[] = [
  {
    title: "Birhanu Nega Celebrating",
    keywords: "celebrating celebration fun happy amharic birhanu",
    slug: "birhanu_nega_celebrating.mp4",
    by: "Community",
  },
  {
    title: "Crack Head Kid",
    keywords: "crack head stupid kid",
    slug: "crack_head_by_robi.mp4",
    by: "Robi",
  },
  {
    title: "Scary stare chicken",
    keywords: "scary stare chiken",
    slug: "scary_stare_chicken_by_selious.mp4",
    by: "Selious",
  },
  {
    title: "Steve ballmer Developer Chant",
    keywords: "developer developers dotnet c# microsoft sweat",
    slug: "steve_ballmer_developer_chant.mp4",
    by: "Community",
  },
  {
    title: "Thank you!",
    keywords: "thank you thanks 10q thanx tnx boy",
    slug: "thank_you_amharic_1.mp4",
    by: "Community",
  },
  {
    title: "Touching grass and crossing",
    keywords:
      "touch grass crossing what christian jesus santa maria cross football kuas",
    slug: "touching_grass_and_crossing_football.mp4",
    by: "Community",
  },
  {
    title: "አመሰግናለው",
    keywords: "thank you thanks thankyou tnx amesegnalew አመሰግናለው",
    slug: "thank_you_amharic_1.mp4",
    by: "Community",
  },
  {
    title: "ከፈለገ ገደል ይግባ",
    keywords: "stfu shut the fuck up I don't give a fuck",
    slug: "i_don_t_give_a_fuck_meles_zenawi_amharic.mp4",
    by: "Community",
  },
  {
    title: "Money show off",
    keywords: "rich poor peasants pleb plebs peasants black lady money showoff",
    slug: "money_show_off_black_lady.mp4",
    by: "Community",
  },
  {
    title: "Cute dog sad sleeping",
    keywords: "cute dog sad sleep lonely single doggo",
    slug: "cute_dog_sad_sleeping.mp4",
    by: "Community",
  },
  {
    title: "Solomon Bogale Crying Seifu show",
    keywords: "solomon bogale crying sad seifu man crying",
    slug: "man_crying_amharic_bogale_amharic.mp4",
    by: "Community",
  },
  {
    title: "Indian Movie Love",
    keywords: "indian movie lovely couple cheesy",
    slug: "indian_movie_love_1.mp4",
    by: "Community",
  },
  {
    title: "Dwight Shrute Scared - The office",
    keywords: "wtf scared shudder dwight the office",
    slug: "dwight_shrute_scared_the_office.mp4",
    by: "Community",
  },
  {
    title: "Bald Kid running slap",
    keywords: "bald cut-g slap kid child running caught",
    slug: "bald_kid_running_slap.mp4",
    by: "Community",
  },
  {
    title: "Indian Movie rich walk",
    keywords: "change india indian walking rich poor magic movie",
    slug: "indian_movie_rich_walk.mp4",
    by: "Community",
  },
  {
    title: "No no wait",
    keywords: "no wait scared tied movie man",
    slug: "no_no_wait_scared_man_1.mp4",
    by: "Community",
  },
  {
    title: "Cartoon sounds",
    keywords: "cartoon tom jerry dumb looney toons",
    slug: "cartoon_sounds_1.mp4",
    by: "Community",
  },
  {
    title: "Hard Work",
    keywords: "hard work construction stupid black",
    slug: "hard_work_parody.mp4",
    by: "Community",
  },
  {
    title: "ምንክን ነው እሚያምክ",
    keywords: "ill tomas comedian stupid help crazy",
    slug: "comedian_thomas_ill.mp4",
    by: "Community",
  },
  {
    title: "Dancing and crying",
    keywords: "dancing crying jam girl",
    slug: "girl_dancing_and_crying.mp4",
    by: "Community",
  },
  {
    title: "Trying hard not to laugh",
    keywords: "lol lmao lmfao trying hard not to laugh football",
    slug: "trying_hard_not_to_laught.mp4",
    by: "Community",
  },
  {
    title: "Best day of my life!",
    keywords: "excited best day of my life foot ball british girl",
    slug: "excited_best_day_of_my_life.mp4",
    by: "Community",
  },
  {
    title: "Ohhh my God!!",
    keywords: "exaggurated oh my God omg african actor",
    slug: "african_actor_oh_my_god.mp4",
    by: "Community",
  },
  {
    title: "Applause!",
    keywords: "man clapping theater applause clap based support",
    slug: "man_clapping_theather.mp4",
    by: "Community",
  },
  {
    title: "Black Chief",
    keywords: "black cheif sexy nsfw",
    slug: "african_cheif_1.mp4",
    by: "Community",
  },
  {
    title: "You Motherfucker!",
    keywords: "mf mother fucker motherfucker piano black dude",
    slug: "black_guy_piano_playing_motherfucker.mp4",
    by: "Community",
  },
  {
    title: "Apes Laugh!",
    keywords: "apes laugh lmao lmfao lol hehe",
    slug: "apes_laughing_at_you.mp4",
    by: "Community",
  },
  {
    title: "LMFAO!",
    keywords: "painful laugh hard lol lmao lmfao",
    slug: "hard_laugh_man_1.mp4",
    by: "Community",
  },
  {
    title: "Noice!!",
    keywords: "noice nice based good",
    slug: "noice_nice.mp4",
    by: "Community",
  },
  {
    title: "Deep down I still love you!",
    keywords: "love you deep down cry sad",
    slug: "deep_down_i_still_love_you.mp4",
    by: "Community",
  },
  {
    title: "Painful laugh!",
    keywords: "painful laugh lol lmao lmfao",
    slug: "painful_hard_laugh_nicolas_cage.mp4",
    by: "Community",
  },
  {
    title: "Face palm",
    keywords: "crowd face palm aye disapointed stupid",
    slug: "crowd_face_palm.mp4",
    by: "Community",
  },
  {
    title: "Mission Passed!",
    keywords: "gta mission passed completed",
    slug: "gta_mission_passed.mp4",
    by: "Community",
  },
  {
    title: "Fuck you all!",
    keywords: "fuck you all stfu shhh",
    slug: "fuck_all_of_them.mp4",
    by: "Community",
  },
  {
    title: "Yummy!",
    keywords: "yummy finger licking",
    slug: "finger_licking.mp4",
    by: "Community",
  },
  {
    title: "Waiting...",
    keywords: "mr bean waiting forever still",
    slug: "mr_bean_waiting.mp4",
    by: "Community",
  },
  {
    title: "I don't give a fuck...",
    keywords: "idgf I don't give a fuck",
    slug: "people_sad_man_sleeping.mp4",
    by: "Community",
  },
  {
    title: "LMFAOOOO",
    keywords: "lmfao lol lmao yesu jesu spanish laugh resitas",
    slug: "resitas_spanish_lauging_jesu.mp4",
    by: "Community",
  },
];
